'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import type { Campaign, Lead, Snapshot } from './types';
const EXAMPLE='Find 20 European robotics startups that could benefit from automated simulation testing.';
const TERMINAL=new Set(['completed','partial','cancelled','budget_exhausted']);
async function api<T>(path:string, method='GET', body?:unknown, key?:string):Promise<T> {
  const response=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined}).catch(()=>{throw new Error('The research service could not be reached. Please try this action again.');});
  let data;try{data=await response.json();}catch{throw new Error('The research service returned an unreadable response. Please try this action again.');}
  if(!response.ok) throw new Error(typeof data?.detail==='string'?data.detail:'The research service could not complete this action. Please try again.');
  return data as T;
}
export default function Home(){
  const [query,setQuery]=useState(''),[mode,setMode]=useState<'demo'|'live'>('demo');
  const [limitsEnabled,setLimitsEnabled]=useState(true);
  const [live,setLive]=useState(false),[state,setState]=useState<Snapshot|null>(null),[history,setHistory]=useState<Campaign[]>([]);
  const [selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const campaignId=state?.campaign.id;
  const historyMenu=useRef<HTMLDetailsElement>(null);
  const pendingRequest=useRef<{query:string;mode:string;key:string}|null>(null);
  async function load(id:string){ const value=await api<Snapshot>('/campaigns/'+id);setState(value);localStorage.setItem('operations.campaign',id);return value; }
  async function recent(){setHistory(await api<Campaign[]>('/campaigns'));}
  useEffect(()=>{api<{live_available:boolean;budget_limits_enabled?:boolean}>('/health').then(x=>{setLive(x.live_available);setLimitsEnabled(x.budget_limits_enabled!==false);}).catch(()=>setError('The research service is unavailable. Check that the local app is running.'));
    recent().catch(()=>setError('Recent runs could not be loaded. Your saved research is still available.')); const id=localStorage.getItem('operations.campaign');if(id)load(id).catch(e=>setError('Saved run could not be restored: '+e.message));
  },[]);
  useEffect(()=>{
    if(!campaignId||!state||TERMINAL.has(state.campaign.status)) return;
    const source=new EventSource('/api/campaigns/'+campaignId+'/events');
    source.onmessage=(event)=>{const value:Snapshot=JSON.parse(event.data);setState(value);if(TERMINAL.has(value.campaign.status)){source.close();recent().catch(()=>setError('Recent runs could not be loaded. Your saved research is still available.'));}};
    source.onerror=()=>{if(source.readyState===EventSource.CLOSED)load(campaignId).catch(()=>setError('Progress connection lost. Reload to restore saved results.'));};
    return ()=>source.close();
  },[campaignId,state?.campaign.status]);
  async function start(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(!pendingRequest.current||pendingRequest.current.query!==query||pendingRequest.current.mode!==mode)pendingRequest.current={query,mode,key:crypto.randomUUID()};const ca=await api<Campaign>('/campaigns','POST',{query,mode},pendingRequest.current.key);setSelected(null);setFilter('all');await load(ca.id);pendingRequest.current=null;await recent();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function action(name:'cancel'|'retry'){if(!campaignId)return;setBusy(true);setError('');try{await api('/campaigns/'+campaignId+'/'+name,'POST',{});await load(campaignId);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function reset(){setState(null);setSelected(null);setQuery('');setError('');localStorage.removeItem('operations.campaign');}
  const running=!!state&&!TERMINAL.has(state.campaign.status);
  const leads=state?.leads.filter(x=>filter==='all'||(filter==='qualified'&&x.qualified)||(filter==='approved'&&x.review_status==='approved'))||[];
  const lead=state?.leads.find(x=>x.id===selected);
  return <main className="shell">
    <header className="header"><a className="brand" href="#" onClick={e=>{e.preventDefault();reset();}}><span className="mark">ao</span>AI Operations</a><div className="header-end"><span className="tagline">Your research, ready to review.</span><details className="history" ref={historyMenu}><summary>Recent runs</summary><div className="history-menu">{history.length?history.map(c=><button key={c.id} onClick={()=>{if(historyMenu.current)historyMenu.current.open=false;setSelected(null);setFilter('all');load(c.id).catch(e=>setError(e.message));}}><strong>{c.criteria.title||c.query}</strong><span>{c.status} · {c.target_count} companies</span></button>):<p>No research yet.</p>}</div></details></div></header>
    {error&&<div role="alert" className="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
    {!state?<section className="hero"><p className="eyebrow">FROM A QUESTION TO QUALIFIED COMPANIES</p><h1>Who are you looking for?</h1><p className="intro">Describe your ideal customer. We’ll find companies, check the evidence, and draft your introduction.</p>
      <form className="composer" onSubmit={start}><label className="sr-only" htmlFor="query">Research request</label><textarea id="query" value={query} onChange={e=>setQuery(e.target.value)} placeholder={EXAMPLE} minLength={8} maxLength={4000} required rows={3}/><div className="composer-bottom"><label className="mode">Research with <select aria-label="Research mode" value={mode} onChange={e=>setMode(e.target.value as 'demo'|'live')}><option value="demo">Demo dataset</option><option value="live" disabled={!live}>Live web</option></select></label><button className="primary" disabled={busy||query.trim().length<8}>{busy?'Starting…':'Start research →'}</button></div></form>
      <div className="examples"><span>Try:</span><button onClick={()=>setQuery(EXAMPLE)}>European robotics startups</button><button onClick={()=>setQuery('Find 20 B2B climate software companies in Europe.')}>B2B climate software</button></div><p className="quiet hero-note">{mode==='demo'?'Demo uses a clearly marked sample dataset. No API keys required.':'Live research uses public web sources. You review every introduction.'+(!limitsEnabled?' Budget limits are off; usage is tracked.':'')}</p>
    </section>:<section className="results">
      <div className="run-heading"><div><p className="eyebrow">{state.campaign.mode==='demo'?'DEMO · ':''}{running?'RESEARCH IN PROGRESS':state.campaign.status==='completed'?'RESEARCH COMPLETE':state.campaign.status.replaceAll('_',' ').toUpperCase()}</p><h1>{state.campaign.criteria.title||'Finding your companies'}</h1><p className="intro"><strong>{state.counts.processed}</strong> of {state.campaign.target_count} researched · {state.counts.qualified} qualified · {state.counts.approved} approved</p></div><div className="actions">{running?<button disabled={busy} onClick={()=>action('cancel')}>Stop research</button>:<button onClick={reset}>New research</button>}<a className={'primary '+(!state.counts.approved?'disabled':'')} aria-disabled={!state.counts.approved} href={state.counts.approved?'/api/campaigns/'+campaignId+'/export?format=csv':undefined} download>Export approved ↓</a></div></div>
      <p className="request"><span>Your request</span>{state.campaign.query}</p>
      {running&&<div className="progress" role="status"><div className="progress-track"><div style={{width:Math.max(3,state.counts.processed/state.campaign.target_count*100)+'%'}}/></div><p>{state.counts.discovered?`${state.counts.discovered} companies found. Collecting evidence and preparing introductions.`:'Interpreting your request and finding company websites…'}</p></div>}
      {(state.campaign.error||state.campaign.status==='cancelled')&&<div className="notice" role="status"><p>{state.campaign.error||'Research stopped. Saved companies and reviewed drafts remain available.'}</p>{(state.campaign.status!=='budget_exhausted'||!state.budget.limits_enabled)&&<button onClick={()=>action('retry')} disabled={busy}>Retry unfinished steps</button>}</div>}
      {state.campaign.mode==='live'&&<UsagePanel state={state}/> }
      <div className="filters" aria-label="Result filters">{[['all','All companies',state.counts.discovered],['qualified','Qualified',state.counts.qualified],['approved','Approved',state.counts.approved]].map(([value,label,count])=><button aria-pressed={filter===value} key={value} onClick={()=>setFilter(String(value))}>{label} <span>{count}</span></button>)}<span className="sorted">Sorted by relevance</span></div>
      <div className="table-wrap"><table><thead><tr><th>Company</th><th>Industry</th><th>Score</th><th>Why it fits</th><th>Review</th></tr></thead><tbody>{leads.map(x=><tr key={x.id}><td><button className="company-link" onClick={()=>setSelected(x.id)}>{x.company_name}</button><span className="domain">{x.domain}</span></td><td>{x.enrichment?.industry||'Researching…'}</td><td><span className="score">{x.qualification?x.qualification.score+' / 100':'—'}</span></td><td>{x.error?<span className="error-text">{x.error}</span>:x.qualification?.reasons[0]||'Collecting source evidence'}</td><td><button className={'review-link '+(x.review_status==='approved'?'approved':'')} onClick={()=>setSelected(x.id)}>{x.review_status==='approved'?'Approved':x.review_status==='rejected'?'Rejected':x.current_revision?'Review →':'View →'}</button></td></tr>)}</tbody></table>{!leads.length&&<div className="empty">{running?'Company results will appear here as research progresses.':'No companies match this filter.'}</div>}</div>
      <div className="run-footer"><details className="logs"><summary>Run logs · {state.logs.length} events</summary><div className="budget">{state.campaign.mode==='demo'?'Sample data · no external calls':`${state.budget.limits_enabled?'Limits on':'Limits off'} · ${state.budget.model_calls}${state.budget.limits_enabled?' / '+state.budget.max_model_calls:''} model requests · ${state.budget.firecrawl_credits}${state.budget.limits_enabled?' / '+state.budget.max_firecrawl_credits:''} Firecrawl credits reserved (all runs)`}</div>{state.logs.map(x=><div className="log" key={x.id}><time>{new Date(x.created_at).toLocaleTimeString()}</time><strong>{x.step}</strong><span>{x.status}{x.attempt>1?` · attempt ${x.attempt}`:''}</span><p>{x.detail}</p>{Object.keys(x.metadata).length>0&&<pre>{JSON.stringify(x.metadata,null,2)}</pre>}</div>)}</details>{state.counts.approved>0&&<a href={'/api/campaigns/'+campaignId+'/export?format=json'} download>Export JSON</a>}</div>
    </section>}
    {lead&&<LeadDrawer lead={lead} demo={state?.campaign.mode==='demo'} onClose={()=>setSelected(null)} onChanged={()=>campaignId?load(campaignId).then(()=>{}):Promise.resolve()}/>}
  </main>;
}
function UsagePanel({state}:{state:Snapshot}){
  const u=state.usage;
  return <section className="usage-panel" aria-label="Research usage">
    <div className="usage-summary"><strong>This run</strong><span>{u.model_requests} model requests</span><span>{u.firecrawl_requests} Firecrawl requests · {u.firecrawl_reserved_credits} credits reserved</span><span className="usage-mode">{state.budget.limits_enabled?'Budget limits on':'Budget limits off'}</span></div>
    <details><summary>Request costs and provider reports</summary>
      <p>{u.tokens_reported_requests?`${u.tokens.total_tokens.toLocaleString()} tokens reported (${u.tokens.prompt_tokens.toLocaleString()} input · ${u.tokens.completion_tokens.toLocaleString()} output), covering ${u.tokens_reported_requests} of ${u.model_requests} model requests.`:'Model token usage has not been reported yet.'}</p>
      <p>{u.firecrawl_reported_credits===null?'Firecrawl has not reported per-request credit charges.':`${u.firecrawl_reported_credits} Firecrawl credits reported, covering ${u.firecrawl_reported_requests} of ${u.firecrawl_requests} requests.`} Reserved credits are an estimate, not a billing receipt. Go subscription usage is not a per-request dollar charge.</p>
      {u.uncertain_requests>0&&<p>{u.uncertain_requests} requests awaiting a complete response or with an uncertain outcome; their reservations are retained.</p>}
      <div className="request-costs">{u.requests.map(r=><div className="request-cost" key={r.id}><time>{new Date(r.created_at).toLocaleTimeString()}</time><strong>{r.provider==='model'?'DeepSeek':'Firecrawl'} · {r.step}</strong><span>{r.provider==='model'?(r.usage.tokens?`${r.usage.tokens.total_tokens.toLocaleString()} tokens`:'Tokens not reported'):`${r.units} reserved · ${r.usage.credits_used===undefined?'charge not reported':r.usage.credits_used+' credits reported'}`}</span><span>{r.status==='reserved'?'Pending / uncertain':`Response ${r.usage.http_status??'received'}`}</span></div>)}</div>
    </details>
  </section>;
}
function LeadDrawer({lead,demo,onClose,onChanged}:{lead:Lead;demo:boolean;onClose:()=>void;onChanged:()=>Promise<void>}){
  const dialog=useRef<HTMLDialogElement>(null);const [subject,setSubject]=useState(lead.subject||''),[body,setBody]=useState(lead.body||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{dialog.current?.showModal();},[]);
  useEffect(()=>{setSubject(lead.subject||'');setBody(lead.body||'');},[lead.id,lead.current_revision]);
  const dirty=subject!==lead.subject||body!==lead.body;
  async function saveIfNeeded(){if(!lead.current_revision)throw new Error('This company has no introduction yet.');if(!dirty)return lead.current_revision;const result=await api<{revision:number}>('/leads/'+lead.id+'/draft','PATCH',{subject,body,expected_revision:lead.current_revision});return result.revision;}
  async function act(decision?:'approved'|'rejected'){setBusy(true);setError('');try{const revision=await saveIfNeeded();if(decision)await api('/leads/'+lead.id+'/review','POST',{revision,decision});await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <dialog className="drawer" ref={dialog} onClose={onClose} aria-label={'Review '+lead.company_name}><div className="drawer-heading"><h2>{lead.company_name}</h2><button aria-label="Close company details" onClick={()=>dialog.current?.close()}>×</button></div><p className="quiet">{lead.enrichment?.industry||lead.status} · {lead.enrichment?.geography||lead.domain}</p>{demo&&<p className="demo-note">Synthetic demo company and source evidence</p>}
    {lead.qualification&&<><div className="fit-score">{lead.qualification.score} / 100 <span>{lead.qualification.verdict.replaceAll('_',' ')}</span></div><p>{lead.enrichment?.summary}</p><ul className="reasons">{lead.qualification.reasons.map((x,i)=><li key={i}>{x}</li>)}</ul></>}
    <h3>Source evidence</h3>{lead.qualification?.evidence.map((e,i)=>{const source=lead.sources.find(s=>s.id===e.source_id);return <div className="evidence" key={i}><blockquote>“{e.quote}”</blockquote><p>{e.claim}</p>{source&&(demo?<span className="source-link">{source.url} · demo source</span>:<a href={source.url} target="_blank" rel="noreferrer">{source.url} ↗</a>)}</div>;})}
    <details className="source-pages"><summary>Source pages · {lead.sources.length}</summary>{lead.sources.map(s=><details key={s.id}><summary>{s.title}</summary><p className="quiet">Collected {new Date(s.fetched_at).toLocaleString()}</p><pre>{s.content}</pre></details>)}</details>
    {lead.current_revision?<><h3>Your introduction</h3><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={240}/></label><label>Message<textarea value={body} onChange={e=>setBody(e.target.value)} rows={9} maxLength={6000}/></label>{error&&<p role="alert" className="error-text">{error}</p>}<div className="drawer-actions"><button className="primary" disabled={busy||!subject.trim()||!body.trim()||(!dirty&&lead.review_status==='approved')} onClick={()=>act('approved')}>{busy?'Saving…':!dirty&&lead.review_status==='approved'?'Approved':'Approve introduction'}</button><button disabled={busy} onClick={()=>act('rejected')}>Reject</button>{dirty&&<button disabled={busy} onClick={()=>act()}>Save changes</button>}</div><p className="quiet">{lead.review_status==='approved'?`Approved revision ${lead.approved_revision}. `:''}You stay in control. Nothing is sent automatically.</p></>:<p className="notice">{lead.status==='failed'?lead.error:lead.qualification?'This company did not meet the qualification threshold.':'The introduction will appear after research and qualification.'}</p>}
  </dialog>;
}
